language: node_js
node_js:
- '0.10'
cache:
  directories:
  - node_modules
  - vendor
before_script:
- npm install
- ./node_modules/.bin/bower install
- ./node_modules/.bin/grunt prod
script: bash ./deploy.sh
